# Generated by Django 4.1.2 on 2022-10-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhoneBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Введите имя", max_length=100, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Введите фамилию",
                        max_length=100,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        help_text="Введите заметку",
                        max_length=400,
                        verbose_name="Заметка",
                    ),
                ),
                (
                    "favourites",
                    models.BooleanField(
                        help_text="Добавить в избранное",
                        verbose_name="Состояние дежурства",
                    ),
                ),
                (
                    "date_of_creation",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату создания контакта",
                        null=True,
                        verbose_name="Дaтa создания контакта",
                    ),
                ),
            ],
        ),
    ]
