# Generated by Django 4.1.2 on 2022-10-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myphonebookapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonebook",
            name="favourites",
            field=models.BooleanField(
                help_text="Добавить в избранное", verbose_name="Избранное"
            ),
        ),
    ]
