# Generated by Django 4.1.2 on 2022-10-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myphonebookapp", "0002_alter_phonebook_favourites"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonebook",
            name="phone",
            field=models.CharField(
                help_text="Введите номер телефона",
                max_length=15,
                null=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
