# Generated by Django 4.1.2 on 2022-10-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myphonebookapp", "0003_phonebook_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonebook",
            name="phone",
            field=models.CharField(
                help_text="Введите номер телефона",
                max_length=15,
                verbose_name="Номер телефона",
            ),
        ),
    ]
